name: "Exportación Automática"
on:
  push:
    branches: [ main, master ] # Se activa al subir a estas ramas

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Exportar Juego
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Exportar Godot
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux_x86_64.zip
          godot_template_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_export_output: true